// Code generated by protoc-gen-go.
// source: sourcehub.proto
// DO NOT EDIT!

/*
Package sourcehub is a generated protocol buffer package.

It is generated from these files:
	sourcehub.proto

It has these top-level messages:
	GetValueRequest
	GetValueResponse
	SetValueRequest
	SetValueResponse
	SubscribeRequest
	SubscribeResponse
*/
package sourcehub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetValueRequest struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *GetValueRequest) Reset()                    { *m = GetValueRequest{} }
func (m *GetValueRequest) String() string            { return proto.CompactTextString(m) }
func (*GetValueRequest) ProtoMessage()               {}
func (*GetValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetValueRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *GetValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetValueResponse struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *GetValueResponse) Reset()                    { *m = GetValueResponse{} }
func (m *GetValueResponse) String() string            { return proto.CompactTextString(m) }
func (*GetValueResponse) ProtoMessage()               {}
func (*GetValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetValueResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetValueRequest struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value  []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *SetValueRequest) Reset()                    { *m = SetValueRequest{} }
func (m *SetValueRequest) String() string            { return proto.CompactTextString(m) }
func (*SetValueRequest) ProtoMessage()               {}
func (*SetValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetValueRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SetValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetValueRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetValueResponse struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *SetValueResponse) Reset()                    { *m = SetValueResponse{} }
func (m *SetValueResponse) String() string            { return proto.CompactTextString(m) }
func (*SetValueResponse) ProtoMessage()               {}
func (*SetValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SetValueResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SubscribeRequest struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SubscribeRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SubscribeRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type SubscribeResponse struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *SubscribeResponse) Reset()                    { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()               {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SubscribeResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*GetValueRequest)(nil), "sourcehub.GetValueRequest")
	proto.RegisterType((*GetValueResponse)(nil), "sourcehub.GetValueResponse")
	proto.RegisterType((*SetValueRequest)(nil), "sourcehub.SetValueRequest")
	proto.RegisterType((*SetValueResponse)(nil), "sourcehub.SetValueResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "sourcehub.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "sourcehub.SubscribeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SourceHub service

type SourceHubClient interface {
	// GetValue expects a source and key and responds with the associated value
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	// SetValue sets the value for the specified source and key
	SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error)
	// Subscribe streams updates to a value for a given source and key
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SourceHub_SubscribeClient, error)
}

type sourceHubClient struct {
	cc *grpc.ClientConn
}

func NewSourceHubClient(cc *grpc.ClientConn) SourceHubClient {
	return &sourceHubClient{cc}
}

func (c *sourceHubClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := grpc.Invoke(ctx, "/sourcehub.SourceHub/GetValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceHubClient) SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error) {
	out := new(SetValueResponse)
	err := grpc.Invoke(ctx, "/sourcehub.SourceHub/SetValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceHubClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SourceHub_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SourceHub_serviceDesc.Streams[0], c.cc, "/sourcehub.SourceHub/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &sourceHubSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SourceHub_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type sourceHubSubscribeClient struct {
	grpc.ClientStream
}

func (x *sourceHubSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SourceHub service

type SourceHubServer interface {
	// GetValue expects a source and key and responds with the associated value
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	// SetValue sets the value for the specified source and key
	SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error)
	// Subscribe streams updates to a value for a given source and key
	Subscribe(*SubscribeRequest, SourceHub_SubscribeServer) error
}

func RegisterSourceHubServer(s *grpc.Server, srv SourceHubServer) {
	s.RegisterService(&_SourceHub_serviceDesc, srv)
}

func _SourceHub_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceHubServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sourcehub.SourceHub/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceHubServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceHub_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceHubServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sourcehub.SourceHub/SetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceHubServer).SetValue(ctx, req.(*SetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceHub_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SourceHubServer).Subscribe(m, &sourceHubSubscribeServer{stream})
}

type SourceHub_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type sourceHubSubscribeServer struct {
	grpc.ServerStream
}

func (x *sourceHubSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SourceHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sourcehub.SourceHub",
	HandlerType: (*SourceHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValue",
			Handler:    _SourceHub_GetValue_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _SourceHub_SetValue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _SourceHub_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sourcehub.proto",
}

func init() { proto.RegisterFile("sourcehub.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xce, 0x2f, 0x2d,
	0x4a, 0x4e, 0xcd, 0x28, 0x4d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x59, 0x73, 0xf1, 0xbb, 0xa7, 0x96, 0x84, 0x25, 0xe6, 0x94, 0xa6, 0x06, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x08, 0x89, 0x71, 0xb1, 0x41, 0xe4, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0,
	0x3c, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x26, 0xb0, 0x20, 0x88, 0xa9, 0xa4, 0xc1,
	0x25, 0x80, 0xd0, 0x5c, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc2, 0xc5, 0x5a, 0x06, 0x12,
	0x00, 0x6b, 0xe6, 0x09, 0x82, 0x70, 0x94, 0x02, 0xb9, 0xf8, 0x83, 0xc9, 0xb5, 0x06, 0x61, 0x24,
	0x33, 0xb2, 0x91, 0x1a, 0x5c, 0x02, 0xc1, 0xc4, 0x59, 0x6e, 0xc3, 0x25, 0x10, 0x5c, 0x9a, 0x54,
	0x9c, 0x5c, 0x94, 0x99, 0x44, 0x86, 0x27, 0x35, 0xb9, 0x04, 0x91, 0x74, 0xe3, 0xb3, 0xc8, 0xe8,
	0x29, 0x23, 0x17, 0x67, 0x30, 0xd8, 0x1c, 0x8f, 0xd2, 0x24, 0x21, 0x57, 0x2e, 0x0e, 0x58, 0xe8,
	0x08, 0x49, 0xe9, 0x21, 0xe2, 0x00, 0x2d, 0xbc, 0xa5, 0xa4, 0xb1, 0xca, 0x41, 0x2c, 0x52, 0x62,
	0x00, 0x19, 0x13, 0x8c, 0xcd, 0x98, 0x60, 0x3c, 0xc6, 0x04, 0x63, 0x1a, 0xe3, 0xc5, 0xc5, 0x09,
	0xf7, 0x86, 0x10, 0x8a, 0x5a, 0xb4, 0xa0, 0x91, 0x92, 0xc1, 0x2e, 0x09, 0x33, 0xc9, 0x80, 0x31,
	0x89, 0x0d, 0x9c, 0x8c, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x46, 0x2b, 0x49, 0x94, 0x59,
	0x02, 0x00, 0x00,
}
