// Code generated by protoc-gen-go.
// source: sourcehub.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sourcehub.proto

It has these top-level messages:
	GetSourcesRequest
	GetSourcesResponse
	GetValueRequest
	GetValueResponse
	SetValueRequest
	SetValueResponse
	GetKeysRequest
	GetKeysResponse
	SubscribeRequest
	SubscribeResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetSourcesRequest struct {
}

func (m *GetSourcesRequest) Reset()                    { *m = GetSourcesRequest{} }
func (m *GetSourcesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSourcesRequest) ProtoMessage()               {}
func (*GetSourcesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetSourcesResponse struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
}

func (m *GetSourcesResponse) Reset()                    { *m = GetSourcesResponse{} }
func (m *GetSourcesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSourcesResponse) ProtoMessage()               {}
func (*GetSourcesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetSourcesResponse) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type GetValueRequest struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *GetValueRequest) Reset()                    { *m = GetValueRequest{} }
func (m *GetValueRequest) String() string            { return proto.CompactTextString(m) }
func (*GetValueRequest) ProtoMessage()               {}
func (*GetValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetValueRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *GetValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetValueResponse struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *GetValueResponse) Reset()                    { *m = GetValueResponse{} }
func (m *GetValueResponse) String() string            { return proto.CompactTextString(m) }
func (*GetValueResponse) ProtoMessage()               {}
func (*GetValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetValueResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetValueRequest struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Value  []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *SetValueRequest) Reset()                    { *m = SetValueRequest{} }
func (m *SetValueRequest) String() string            { return proto.CompactTextString(m) }
func (*SetValueRequest) ProtoMessage()               {}
func (*SetValueRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SetValueRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SetValueRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetValueRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetValueResponse struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *SetValueResponse) Reset()                    { *m = SetValueResponse{} }
func (m *SetValueResponse) String() string            { return proto.CompactTextString(m) }
func (*SetValueResponse) ProtoMessage()               {}
func (*SetValueResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SetValueResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetKeysRequest struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
}

func (m *GetKeysRequest) Reset()                    { *m = GetKeysRequest{} }
func (m *GetKeysRequest) String() string            { return proto.CompactTextString(m) }
func (*GetKeysRequest) ProtoMessage()               {}
func (*GetKeysRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetKeysRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type GetKeysResponse struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetKeysResponse) Reset()                    { *m = GetKeysResponse{} }
func (m *GetKeysResponse) String() string            { return proto.CompactTextString(m) }
func (*GetKeysResponse) ProtoMessage()               {}
func (*GetKeysResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetKeysResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type SubscribeRequest struct {
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SubscribeRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SubscribeRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type SubscribeResponse struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *SubscribeResponse) Reset()                    { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()               {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SubscribeResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*GetSourcesRequest)(nil), "sourcehub.pb.GetSourcesRequest")
	proto.RegisterType((*GetSourcesResponse)(nil), "sourcehub.pb.GetSourcesResponse")
	proto.RegisterType((*GetValueRequest)(nil), "sourcehub.pb.GetValueRequest")
	proto.RegisterType((*GetValueResponse)(nil), "sourcehub.pb.GetValueResponse")
	proto.RegisterType((*SetValueRequest)(nil), "sourcehub.pb.SetValueRequest")
	proto.RegisterType((*SetValueResponse)(nil), "sourcehub.pb.SetValueResponse")
	proto.RegisterType((*GetKeysRequest)(nil), "sourcehub.pb.GetKeysRequest")
	proto.RegisterType((*GetKeysResponse)(nil), "sourcehub.pb.GetKeysResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "sourcehub.pb.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "sourcehub.pb.SubscribeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SourceHub service

type SourceHubClient interface {
	// GetSources responds with a stream of objects representing available sources
	GetSources(ctx context.Context, in *GetSourcesRequest, opts ...grpc.CallOption) (SourceHub_GetSourcesClient, error)
	// GetValue expects a source and key and responds with the associated value
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	// SetValue sets the value for the specified source and key
	SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error)
	// GetKeys expects a source and responds with a stream of objects representing available keys
	GetKeys(ctx context.Context, in *GetKeysRequest, opts ...grpc.CallOption) (SourceHub_GetKeysClient, error)
	// Subscribe streams updates to a value for a given source and key
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SourceHub_SubscribeClient, error)
}

type sourceHubClient struct {
	cc *grpc.ClientConn
}

func NewSourceHubClient(cc *grpc.ClientConn) SourceHubClient {
	return &sourceHubClient{cc}
}

func (c *sourceHubClient) GetSources(ctx context.Context, in *GetSourcesRequest, opts ...grpc.CallOption) (SourceHub_GetSourcesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SourceHub_serviceDesc.Streams[0], c.cc, "/sourcehub.pb.SourceHub/GetSources", opts...)
	if err != nil {
		return nil, err
	}
	x := &sourceHubGetSourcesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SourceHub_GetSourcesClient interface {
	Recv() (*GetSourcesResponse, error)
	grpc.ClientStream
}

type sourceHubGetSourcesClient struct {
	grpc.ClientStream
}

func (x *sourceHubGetSourcesClient) Recv() (*GetSourcesResponse, error) {
	m := new(GetSourcesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sourceHubClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := grpc.Invoke(ctx, "/sourcehub.pb.SourceHub/GetValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceHubClient) SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error) {
	out := new(SetValueResponse)
	err := grpc.Invoke(ctx, "/sourcehub.pb.SourceHub/SetValue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceHubClient) GetKeys(ctx context.Context, in *GetKeysRequest, opts ...grpc.CallOption) (SourceHub_GetKeysClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SourceHub_serviceDesc.Streams[1], c.cc, "/sourcehub.pb.SourceHub/GetKeys", opts...)
	if err != nil {
		return nil, err
	}
	x := &sourceHubGetKeysClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SourceHub_GetKeysClient interface {
	Recv() (*GetKeysResponse, error)
	grpc.ClientStream
}

type sourceHubGetKeysClient struct {
	grpc.ClientStream
}

func (x *sourceHubGetKeysClient) Recv() (*GetKeysResponse, error) {
	m := new(GetKeysResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sourceHubClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (SourceHub_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SourceHub_serviceDesc.Streams[2], c.cc, "/sourcehub.pb.SourceHub/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &sourceHubSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SourceHub_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type sourceHubSubscribeClient struct {
	grpc.ClientStream
}

func (x *sourceHubSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SourceHub service

type SourceHubServer interface {
	// GetSources responds with a stream of objects representing available sources
	GetSources(*GetSourcesRequest, SourceHub_GetSourcesServer) error
	// GetValue expects a source and key and responds with the associated value
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	// SetValue sets the value for the specified source and key
	SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error)
	// GetKeys expects a source and responds with a stream of objects representing available keys
	GetKeys(*GetKeysRequest, SourceHub_GetKeysServer) error
	// Subscribe streams updates to a value for a given source and key
	Subscribe(*SubscribeRequest, SourceHub_SubscribeServer) error
}

func RegisterSourceHubServer(s *grpc.Server, srv SourceHubServer) {
	s.RegisterService(&_SourceHub_serviceDesc, srv)
}

func _SourceHub_GetSources_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSourcesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SourceHubServer).GetSources(m, &sourceHubGetSourcesServer{stream})
}

type SourceHub_GetSourcesServer interface {
	Send(*GetSourcesResponse) error
	grpc.ServerStream
}

type sourceHubGetSourcesServer struct {
	grpc.ServerStream
}

func (x *sourceHubGetSourcesServer) Send(m *GetSourcesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SourceHub_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceHubServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sourcehub.pb.SourceHub/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceHubServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceHub_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceHubServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sourcehub.pb.SourceHub/SetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceHubServer).SetValue(ctx, req.(*SetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceHub_GetKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetKeysRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SourceHubServer).GetKeys(m, &sourceHubGetKeysServer{stream})
}

type SourceHub_GetKeysServer interface {
	Send(*GetKeysResponse) error
	grpc.ServerStream
}

type sourceHubGetKeysServer struct {
	grpc.ServerStream
}

func (x *sourceHubGetKeysServer) Send(m *GetKeysResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SourceHub_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SourceHubServer).Subscribe(m, &sourceHubSubscribeServer{stream})
}

type SourceHub_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type sourceHubSubscribeServer struct {
	grpc.ServerStream
}

func (x *sourceHubSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SourceHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sourcehub.pb.SourceHub",
	HandlerType: (*SourceHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValue",
			Handler:    _SourceHub_GetValue_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _SourceHub_SetValue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSources",
			Handler:       _SourceHub_GetSources_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetKeys",
			Handler:       _SourceHub_GetKeys_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _SourceHub_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sourcehub.proto",
}

func init() { proto.RegisterFile("sourcehub.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xff, 0x69, 0xfe, 0x56, 0x33, 0x14, 0x93, 0x8e, 0x22, 0x25, 0x58, 0x5b, 0xd6, 0x4b,
	0x04, 0x09, 0xa2, 0x47, 0x3d, 0x79, 0x89, 0xd8, 0x8b, 0x66, 0xc1, 0x83, 0x37, 0xb7, 0x0c, 0x28,
	0x8a, 0x89, 0xd9, 0xac, 0xd0, 0x6f, 0xe2, 0xc7, 0x95, 0x24, 0x5b, 0xb3, 0x34, 0x6c, 0x95, 0xde,
	0xb2, 0xb3, 0xf3, 0x7e, 0x6f, 0x77, 0xde, 0x06, 0x7c, 0x99, 0xa9, 0x62, 0x4e, 0xcf, 0x4a, 0xc4,
	0x79, 0x91, 0x95, 0x19, 0x0e, 0x8c, 0x82, 0x60, 0x7b, 0x30, 0x4c, 0xa8, 0xe4, 0x75, 0x49, 0xa6,
	0xf4, 0xa1, 0x48, 0x96, 0xec, 0x14, 0xd0, 0x2c, 0xca, 0x3c, 0x7b, 0x97, 0x84, 0x07, 0xd0, 0x6f,
	0xa4, 0x23, 0x67, 0xea, 0x44, 0x5e, 0xaa, 0x57, 0xec, 0x12, 0xfc, 0x84, 0xca, 0x87, 0xa7, 0x37,
	0x45, 0x1a, 0x60, 0x6b, 0xc5, 0x00, 0xdc, 0x57, 0x5a, 0x8c, 0x7a, 0x75, 0xb1, 0xfa, 0x64, 0x11,
	0x04, 0xad, 0x58, 0x1b, 0xed, 0xc3, 0xd6, 0x67, 0x55, 0xa8, 0xc5, 0x83, 0xb4, 0x59, 0xb0, 0x7b,
	0xf0, 0xf9, 0xa6, 0x36, 0x2d, 0xd2, 0x35, 0x91, 0x11, 0x04, 0xfc, 0x6f, 0xe6, 0x11, 0xec, 0x26,
	0x54, 0xce, 0x68, 0x21, 0x7f, 0xf1, 0x66, 0xc7, 0xf5, 0x34, 0x9a, 0x4e, 0x8d, 0xd4, 0xc7, 0x71,
	0xda, 0x5b, 0x5f, 0x41, 0xc0, 0x95, 0x90, 0xf3, 0xe2, 0x45, 0x6c, 0x30, 0xb3, 0x13, 0x18, 0x1a,
	0xea, 0x75, 0xe7, 0x3e, 0xff, 0x72, 0xc1, 0x6b, 0x72, 0xbc, 0x51, 0x02, 0x39, 0x40, 0x9b, 0x2b,
	0x4e, 0x62, 0xf3, 0x25, 0xc4, 0x9d, 0x67, 0x10, 0x4e, 0xed, 0x0d, 0x8d, 0x29, 0xfb, 0x77, 0xe6,
	0xe0, 0x0c, 0x76, 0x96, 0x09, 0xe2, 0xb8, 0xa3, 0x30, 0xf3, 0x0a, 0x8f, 0x6c, 0xdb, 0x4b, 0x5c,
	0x05, 0xe3, 0x16, 0x18, 0x5f, 0x0f, 0xe3, 0x5d, 0xd8, 0x2d, 0x6c, 0xeb, 0x28, 0xf0, 0xb0, 0xe3,
	0x6c, 0x64, 0x19, 0x8e, 0x2d, 0xbb, 0xc6, 0x2d, 0xef, 0xc0, 0xfb, 0x99, 0x39, 0xae, 0x5a, 0xaf,
	0x44, 0x19, 0x4e, 0xac, 0xfb, 0x2d, 0xf1, 0xfa, 0xff, 0x63, 0x2f, 0x17, 0xa2, 0x5f, 0xff, 0x94,
	0x17, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x39, 0x40, 0xab, 0x5b, 0xa7, 0x03, 0x00, 0x00,
}
